spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/db_mahasiswa?createDatabaseIfNotExist=true&autoReconnect=true&serverTimezone=Asia/Jakarta
  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: update
      debug: true